// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO Entry (
    account_id,
    amount
) VALUES (
    $1,
    $2
)
RETURNING id, account_id, amount, created_at
`

type CreateEntryParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AccountID, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM Entry WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const deleteEntryByAccount = `-- name: DeleteEntryByAccount :exec
DELETE FROM Entry WHERE account_id = $1
`

func (q *Queries) DeleteEntryByAccount(ctx context.Context, accountID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntryByAccount, accountID)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT id, account_id, amount, created_at FROM Entry WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntryByAccount = `-- name: GetEntryByAccount :many
SELECT id, account_id, amount, created_at FROM Entry WHERE account_id = $1
`

func (q *Queries) GetEntryByAccount(ctx context.Context, accountID int64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntryByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE Entry SET
    account_id = $1,
    amount = $2
WHERE id = $3
RETURNING id, account_id, amount, created_at
`

type UpdateEntryParams struct {
	AccountID int64 `json:"account_id"`
	Amount    int64 `json:"amount"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, updateEntry, arg.AccountID, arg.Amount, arg.ID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const updateEntryByAccount = `-- name: UpdateEntryByAccount :many
UPDATE Entry SET
    account_id = $1,
    amount = $2
WHERE account_id = $3
RETURNING id, account_id, amount, created_at
`

type UpdateEntryByAccountParams struct {
	AccountID   int64 `json:"account_id"`
	Amount      int64 `json:"amount"`
	AccountID_2 int64 `json:"account_id_2"`
}

func (q *Queries) UpdateEntryByAccount(ctx context.Context, arg UpdateEntryByAccountParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, updateEntryByAccount, arg.AccountID, arg.Amount, arg.AccountID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
